name: Aggregator BDD tests

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  aggregator-bdd:
    name: BDD tests
    uses: LukenLarra/processing-tools/.github/workflows/bdd.yaml@feature-parallel-execution
    with:
      service: insights-results-aggregator 
      use_kafka: true
      use_postgres: true
      postgres_version: "13.9"
      parallel_execution: false

  dvo-bdd:
    name: DVO BDD tests
    uses: LukenLarra/processing-tools/.github/workflows/bdd.yaml@feature-parallel-execution
    with:
      service: dvo-writer
      use_kafka: true
      use_postgres: true
      parallel_execution: false
